Repository team-nk/kim-il-jeong-android, pull requests merged in 2022-11, with the labels that each got.

#90 PR :: (#74) 로그인 서버 연동 구현 🍙
  app/src/main/java/com/teamnk/kimiljung/data/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/data/Connection.kt
  app/src/main/java/com/teamnk/kimiljung/data/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/data/api/LoginAPI.kt
  app/src/main/java/com/teamnk/kimiljung/data/model/login/LoginRequest.kt
  app/src/main/java/com/teamnk/kimiljung/data/model/login/LoginResponse.kt
  app/src/main/java/com/teamnk/kimiljung/data/repository/login/LoginRepository.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/login/view/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/register/view/RegisterActivity.kt
  app/src/main/res/values/strings.xml
Labels: 기능 추가, 기능 수정, 코드 리팩토링

#97 PR :: (#95) 회원가입 기능 구현
  app/src/main/java/com/teamnk/kimiljung/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/api/AuthAPI.kt
  app/src/main/java/com/teamnk/kimiljung/api/LoginAPI.kt
  app/src/main/java/com/teamnk/kimiljung/api/RegisterAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterViewModel.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#102 PR :: (#86) 커스텀 캘린더 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/feature/fragment/calendar/CalendarDecorator.kt
  app/src/main/java/com/teamnk/kimiljung/feature/fragment/calendar/CalendarFragment.kt
  app/src/main/res/drawable/background_bottom_navigation.xml
  app/src/main/res/drawable/background_bottom_navigation_icon.xml
  app/src/main/res/drawable/background_calendar.xml
  app/src/main/res/drawable/background_calendar_date_today.xml
  app/src/main/res/values/styles.xml
Labels: 기능 수정, 코드 리팩토링

#104 PR :: (#103) 기본 선택된 Bottom Navigation Item을 Calendar로 변경
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
Labels: 기능 추가, 기능 수정, 버그 수정

#105 PR :: (#94) 지도 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/feature/fragment/map/MapFragment.kt
  app/src/main/res/layout/fragment_map.xml
Labels: 기능 추가

#110 PR :: (#108) 마이페이지 정보 변경하기 UI 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/fragment/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_change_user_information.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#112 PR :: (#111) 비밀번호 변경 페이지 UI 구성 🧇
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordActivity.kt
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#116 PR :: (#115) 게시글 페이지 구현 🌮
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/CreateNewPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/PostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/PostCommentActivity.kt
  app/src/main/res/drawable/background_text_input.xml
  app/src/main/res/drawable/icon_send.xml
  app/src/main/res/drawable/img_logo_post.png
  app/src/main/res/layout/activity_create_new_post.xml
  app/src/main/res/layout/activity_post.xml
  app/src/main/res/layout/activity_post_comment.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#118 PR :: (#114) 일정 바텀 시트 구현
  app/src/main/java/com/teamnk/kimiljung/feature/fragment/calendar/CalendarFragment.kt
  app/src/main/res/drawable/all_button_delete.xml
  app/src/main/res/layout/dialog_map_location.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#121 PR :: (#120) 내 글 확인하기 페이지 UI 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/PostHistoryActivity.kt
  app/src/main/res/layout/activity_post_history.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#123 PR :: (#122) Post 페이지 Floating Action Button UI 구성
  app/src/main/res/layout/dialog_schedule_addiction.xml
  app/src/main/res/layout/dialog_select_schedule.xml
  app/src/main/res/layout/fragment_select_schedule.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#125 PR :: (#120) 내 글 확인하기 페이지 UI 구성
  app/src/main/res/drawable/icon_ping.xml
  app/src/main/res/layout/dialog_select_specific_schedule.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#126 PR :: (#122) Post 페이지 Floating Action Button UI 구성
  app/src/main/res/drawable/background_fragment_post_post_floating_action_button.xml
  app/src/main/res/drawable/icon_pencil.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가, 기능 수정

#128 PR :: (#124) 코드 성형수술 💉 - 2
  app/src/main/java/com/teamnk/kimiljung/feature/calendar/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/res/drawable/background_activity_post_comment_text_input.xml
  app/src/main/res/drawable/background_button_delete.xml
  app/src/main/res/drawable/background_button_secondary.xml
  app/src/main/res/drawable/background_dialog_create_schedule_time.xml
  app/src/main/res/drawable/background_floating_action_button_fragment_post_post.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_change_user_information.xml
  app/src/main/res/layout/activity_create_new_post.xml
  app/src/main/res/layout/activity_introduction_pager.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_post_comment.xml
  app/src/main/res/layout/activity_post_history.xml
  app/src/main/res/layout/activity_post_inspect.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/dialog_create_schedule.xml
  app/src/main/res/layout/dialog_double_button.xml
  app/src/main/res/layout/dialog_enter_birthday.xml
  app/src/main/res/layout/dialog_map_location.xml
  app/src/main/res/layout/dialog_select_schedule.xml
  app/src/main/res/layout/dialog_select_specific_schedule.xml
  app/src/main/res/layout/dialog_single_button.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_introduction_pager.xml
  app/src/main/res/menu/menu_bottom_navigation_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 수정, 코드 리팩토링

#129 PR :: (#124) 코드 성형수술 💉 - 3
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_change_user_information.xml
  app/src/main/res/layout/activity_create_new_post.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_post_comment.xml
  app/src/main/res/layout/activity_post_history.xml
  app/src/main/res/layout/activity_post_inspect.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/dialog_create_schedule.xml
  app/src/main/res/layout/dialog_double_button.xml
  app/src/main/res/layout/dialog_enter_birthday.xml
  app/src/main/res/layout/dialog_map_location.xml
  app/src/main/res/layout/dialog_select_schedule.xml
  app/src/main/res/layout/dialog_select_specific_schedule.xml
  app/src/main/res/layout/dialog_single_button.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/styles.xml
Labels: 기능 수정, 코드 리팩토링

#131 PR :: (#130) 버튼의 눌리는 효과 구현
  app/src/main/res/drawable/background_button_delete.xml
  app/src/main/res/drawable/background_button_primary.xml
  app/src/main/res/drawable/background_button_secondary.xml
  app/src/main/res/values/colors.xml
Labels: 기능 추가, 기능 수정

#133 PR :: (#132) 로그인 로직 재구성
  app/src/main/res/layout/activity_introduction_pager.xml
Labels: 기능 수정, 코드 리팩토링

#134 PR :: (#100) 아이디 중복 확인 로직 구현 및 회원가입/로그인 로직 일부 구현
  app/src/main/java/com/teamnk/kimiljung/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/api/RegisterAPI.kt
  app/src/main/java/com/teamnk/kimiljung/api/Tokens.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 기능 추가, 기능 수정, 코드 리팩토링
