Repository team-nk/kim-il-jeong-android, pull requests merged in 2022-12, with the labels that each got.

#139 PR :: (#135) 마이페이지 로직 구현 - 1
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/ChangePasswordActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageRepository.kt
  app/src/main/res/values/strings.xml
Labels: 기능 수정, 코드 리팩토링

#142 PR :: (#135) 마이페이지 로직 구현 - 2
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageFragment.kt
Labels: 기능 추가, 기능 수정, 코드 리팩토링

#143 PR :: (#135) 마이페이지 로직 구현 - 3
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 기능 수정

#145 PR :: (#144) 지도 초기화 오류 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/teamnk/kimiljung/feature/map/MapFragment.kt
Labels: 버그 수정

#146 PR :: (#109) 내 위치 표시 기능 구현
  app/src/main/java/com/teamnk/kimiljung/feature/fragment/map/MapFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/introduction/IntroductionPagerActivity.kt
Labels: 기능 추가

#148 PR :: (#147) 내 정보 조회 기능 구현
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/util/Constans.kt
Labels: 기능 수정

#150 PR :: (#149) 지도 초기화 버그 수정
  app/src/main/java/com/teamnk/kimiljung/feature/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/map/MapFragment.kt
  app/src/main/res/values/strings.xml
Labels: 버그 수정

#153 PR :: (#152) 게시글 목록 UI 퍼블리싱
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostData.kt
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#157 PR :: (#155) 게시글 조회 서버 연동
  app/src/main/java/com/teamnk/kimiljung/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostViewModelFactory.kt
  app/src/main/res/layout/item_post.xml
Labels: 기능 추가

#159 PR :: 5-로그인-로직-재구성 1
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/teamnk/kimiljung/common/BooleanResponse.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterViewModelFactory.kt
  app/src/main/res/values/strings.xml
Labels: 기능 수정

#160 PR :: (#158) 게시글 상세보기 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostAdapter.kt
  app/src/main/res/layout/activity_detail_post.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#163 PR :: (#161) 댓글 페이지 퍼블리싱
  app/src/main/res/drawable/background_text_input_surface_secondary.xml
  app/src/main/res/drawable/icon_write_comment.png
  app/src/main/res/layout/activity_comment.xml
  app/src/main/res/layout/item_comment.xml
Labels: 기능 추가

#165 PR :: (#164) 댓글 페이지 서버 연동
  app/build.gradle
  app/src/main/java/com/teamnk/kimiljung/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentListResponse.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
  app/src/main/res/layout/activity_comment.xml
  app/src/main/res/layout/activity_detail_post.xml
  app/src/main/res/layout/activity_post_comment.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#166 PR :: (#132) 로그인 로직 재구성
  .idea/intellij-javadocs-4.0.1.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/common/BooleanResponse.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/util/Extensions.kt
  app/src/main/java/com/teamnk/kimiljung/util/ToastUtil.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가, 기능 수정

#169 PR :: (#Feature/168) startactivityutil cleanup
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/util/StartActivityUtil.kt
Labels: 기능 수정, 코드 리팩토링

#171 PR :: (#167) post comment
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/PostData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentRequest.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentAdapter.kt
  app/src/main/res/layout/activity_post_comment.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가
