Repository team-nk/kim-il-jeong-android, pull requests merged in 2022-10, with the labels that each got.

#21 PR :: (#20) refactor ids, methods ...
  app/build.gradle
  app/src/main/java/com/teamnk/kimiljung/activity/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/adapter/introduction/IntroductionPagerAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/data/Connection.kt
  app/src/main/java/com/teamnk/kimiljung/util/BindingUtil.kt
  app/src/main/java/com/teamnk/kimiljung/util/SharedPreferencesUtil.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable/introduction_icon_next.png
  app/src/main/res/drawable/introduction_pager_image_1.png
  app/src/main/res/drawable/introduction_pager_image_2.png
  app/src/main/res/drawable/introduction_pager_image_3.png
  app/src/main/res/drawable/introduction_pager_image_4.png
  app/src/main/res/drawable/introduction_text_next.png
  app/src/main/res/drawable/start_icon_google.png
  app/src/main/res/drawable/start_icon_kakao.png
  app/src/main/res/drawable/start_logo_initial.png
  app/src/main/res/layout/activity_introduction_pager.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_start.xml
Labels: 기능 추가, 기능 수정, 코드 리팩토링

#23 22 Binding 메모리 중복 할당 문제 해결
  app/src/main/java/com/teamnk/kimiljung/activity/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/util/BindingUtil.kt
Labels: 코드 리팩토링, 버그 수정

#25 PR :: (#24) 회원가입 Dialog 로직 구현
  app/src/main/java/com/teamnk/kimiljung/activity/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/dto/LoginResponse.kt
  app/src/main/java/com/teamnk/kimiljung/util/DialogUtil.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/dialog_all_single_button.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 기능 수정, 코드 리팩토링

#27 PR :: (#26) MVVM 아키텍처 패턴 적용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/activity/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/auth/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/dto/LoginRequest.kt
  app/src/main/java/com/teamnk/kimiljung/repository/auth/LoginRepository.kt
  app/src/main/java/com/teamnk/kimiljung/util/BindingUtil.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/IntroductionPagerViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_introduction_pager.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: 기능 추가, 기능 수정, 코드 리팩토링

#32 PR :: (#28) 회원가입 로직 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/teamnk/kimiljung/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/auth/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/data/RegisterApi.kt
  app/src/main/java/com/teamnk/kimiljung/dto/DuplicateRequest.kt
  app/src/main/java/com/teamnk/kimiljung/dto/VerifyCodeRequest.kt
  app/src/main/java/com/teamnk/kimiljung/dto/VerifyRequest.kt
  app/src/main/java/com/teamnk/kimiljung/repository/auth/RegisterRepository.kt
  app/src/main/java/com/teamnk/kimiljung/util/ToastUtil.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/RegisterViewModel.kt
Labels: 기능 추가

#33 PR :: (#29) 메인 페이지 로직 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/teamnk/kimiljung/activity/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/base/BaseFragment.kt
  app/src/main/java/com/teamnk/kimiljung/fragment/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/fragment/MapFragment.kt
  app/src/main/java/com/teamnk/kimiljung/fragment/NotificationFragment.kt
  app/src/main/java/com/teamnk/kimiljung/fragment/UserFragment.kt
  app/src/main/res/drawable/all_logo_login.png
  app/src/main/res/drawable/background_bn.xml
  app/src/main/res/drawable/background_bn_icon.xml
  app/src/main/res/drawable/bn_main_color_selector.xml
  app/src/main/res/drawable/icon_calendar.xml
  app/src/main/res/drawable/icon_map.xml
  app/src/main/res/drawable/icon_notification.xml
  app/src/main/res/drawable/icon_user.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/dialog_all_single_button.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_user.xml
  app/src/main/res/menu/menu_main_bottom_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 기능 수정

#34 PR :: (#30) 디렉토리 정리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/data/LoginApi.kt
  app/src/main/java/com/teamnk/kimiljung/data/RegisterApi.kt
  app/src/main/java/com/teamnk/kimiljung/data/dto/DuplicateRequest.kt
  app/src/main/java/com/teamnk/kimiljung/data/dto/LoginRequest.kt
  app/src/main/java/com/teamnk/kimiljung/data/dto/LoginResponse.kt
  app/src/main/java/com/teamnk/kimiljung/data/dto/VerifyCodeRequest.kt
  app/src/main/java/com/teamnk/kimiljung/data/dto/VerifyRequest.kt
  app/src/main/java/com/teamnk/kimiljung/repository/auth/LoginRepository.kt
  app/src/main/java/com/teamnk/kimiljung/repository/auth/RegisterRepository.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/adapter/introduction/IntroductionPagerAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/MapFragment.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/NotificationFragment.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/UserFragment.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/RegisterViewModel.kt
  app/src/main/res/layout/activity_introduction_pager.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_start.xml
Labels: 코드 리팩토링

#35 PR :: (#29) 메인 페이지 로직 2
  app/src/main/java/com/teamnk/kimiljung/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable/background_bn_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/menu/menu_main_bottom_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 기능 수정, 코드 리팩토링

#42 PR :: (#29) 메인 페이지 로직 구현 3
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가, 기능 수정

#50 PR :: (#49) ViewModel 사용 로직 변경
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/RegisterViewModel.kt
Labels: 기능 수정, 버그 수정

#51 PR :: (#45) 마이페이지 UI 구성 1 🍔
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/res/drawable-v24/icon_mypage_depth.svg
  app/src/main/res/drawable-v24/img_blank.jpeg
  app/src/main/res/drawable-v24/mypage_logo_mypage_title.png
  app/src/main/res/drawable/icon_edit.xml
  app/src/main/res/drawable/mypage_button_primary.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/dialog_all_single_button.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 코드 리팩토링

#52 PR :: (#45) 마이페이지 UI 구성 1 - 1 🍔
  app/src/main/res/drawable-v24/icon_mypage_depth.svg
  app/src/main/res/drawable/icon_mypage_depth.xml
Labels: 기능 추가, 코드 리팩토링

#53 PR :: (#45) 마이페이지 UI 구성 1 - 2 🍔
  app/src/main/res/layout/fragment_mypage.xml
Labels: 기능 추가, 코드 리팩토링

#55 PR :: (#45) 마이페이지 UI 구성 1 - 3 🍔
  .idea/kotlinScripting.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가, 코드 리팩토링

#61 PR :: (#45) 마이페이지 UI 구성, 스크롤바 제거 🍔
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
  app/src/main/res/layout/fragment_mypage.xml
Labels: 기능 수정

#62 PR :: (#60) 화면 재접속 시 선텍되는 BottomNavigationView Menu와 Fragment가 일치하지 않는 현상 🍩
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
Labels: 기능 수정, 버그 수정

#63 PR :: (#56) UI 구성 변경 시 프래그먼트가 초기화되는 이슈 🍤
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
Labels: 기능 수정, 버그 수정

#68 PR :: (#67) SharedPreferences와 Editor를 상수로 만들기 🫖
  app/src/main/java/com/teamnk/kimiljung/base/BaseFragment.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/util/Constans.kt
  app/src/main/java/com/teamnk/kimiljung/util/SharedPreferencesUtil.kt
Labels: 기능 추가, 기능 수정

#71 PR :: (#47) 로그아웃 로직 구현 2🧋
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/util/Constans.kt
  app/src/main/java/com/teamnk/kimiljung/util/SharedPreferencesUtil.kt
Labels: 기능 추가, 기능 수정

#72 PR :: (#64) ViewModel Factory 생성 🍘
  app/src/main/java/com/teamnk/kimiljung/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/auth/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/activity/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/util/Constans.kt
  app/src/main/java/com/teamnk/kimiljung/util/SharedPreferencesUtil.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/MainViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/auth/LoginViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/auth/LoginViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/auth/RegisterViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/viewmodel/introduction/IntroductionPagerViewModel.kt
  app/src/main/res/layout/activity_introduction_pager.xml
Labels: 기능 수정, 코드 리팩토링

#73 PR :: (#47) 로그아웃 로직 구현 🧋
  app/src/main/java/com/teamnk/kimiljung/ui/activity/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/MyPageFragment.kt
Labels: 기능 수정, 버그 수정

#75 70_캘린더_퍼블리싱
  app/build.gradle
  app/src/main/java/com/teamnk/kimiljung/ui/MainCalendarViewManager.kt
  app/src/main/java/com/teamnk/kimiljung/ui/fragment/CalendarFragment.kt
  app/src/main/res/drawable/background_selected_date.xml
  app/src/main/res/drawable/calendar_logo_calendar_title.png
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_mypage.xml
  gradle.properties
  settings.gradle
Labels: 기능 추가

#81 PR :: (#79) 패키지 정리 Conflicts로 인한 코드 리팩토링
  app/src/main/java/com/teamnk/kimiljung/presentation/calendar/view/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/calendar/view/CalendarFragment.kt~Stashed changes_0
  app/src/main/java/com/teamnk/kimiljung/presentation/calendar/view/CalendarFragment.kt~Updated upstream
  app/src/main/java/com/teamnk/kimiljung/presentation/calendar/view/CalendarFragment.kt~Updated upstream_0
  app/src/main/java/com/teamnk/kimiljung/presentation/introduction/view/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/login/view/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/fragment/calendar/CalendarViewManager.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/fragment/calendar/view/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/fragment/map/view/MapFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/fragment/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/fragment/notification/view/NotificationFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/view/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/register/view/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/register/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/start/view/StartActivity.kt
  app/src/main/res/layout/activity_introduction_pager.xml
Labels: 기능 수정, 코드 리팩토링, 버그 수정

#82 PR :: (#65) ViewModel 가변 데이터 노출 제한 (MutableLiveData -> LiveData) 🍦
  app/src/main/java/com/teamnk/kimiljung/presentation/login/view/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/register/viewmodel/RegisterViewModel.kt
Labels: 기능 수정

#83 PR :: (#30) 디렉토리 정리가 필요합니다
  .idea/vcs.xml
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/calendar/CalendarViewManager.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/calendar/view/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/map/view/MapFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/notification/view/NotificationFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/view/MainActivity.kt
Labels: 코드 리팩토링

#84 PR :: (#77) Retrofit 관련 클래스 구성 🥟
  .gitignore
  app/build.gradle
  app/src/main/java/com/teamnk/kimiljung/common/Constant.kt
  app/src/main/java/com/teamnk/kimiljung/data/api/RetrofitClient.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: 기능 추가, 기능 수정

#87 PR :: (#76) fragment_calendar xml view 리팩토링 필요!! 🍔
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/values/strings.xml
Labels: 기능 수정, 코드 리팩토링

#88 PR :: (#80) LAUNCHER Activity를 MainActivity로 변경 🥠
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/presentation/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/base/BaseFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/calendar/view/CalendarFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/fragment/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/introduction/adapter/IntroductionPagerAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/introduction/view/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/login/view/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/main/view/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/register/view/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/presentation/start/view/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/util/Constans.kt
  app/src/main/java/com/teamnk/kimiljung/util/IntentUtil.kt
Labels: 기능 수정, 코드 리팩토링
