Repository team-nk/kim-il-jeong-android, pull requests merged in 2023-01, with the labels that each got.

#175 PR :: (#174) 유저 권한 처리 로직 수정
  app/src/main/java/com/teamnk/kimiljung/feature/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/map/MapFragment.kt
  app/src/main/res/values/strings.xml
Labels: 기능 수정

#177 PR :: (#Feature/135) 마이페이지 로직 구현 - 1
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamnk/kimiljung/api/RetrofitClient.kt
  app/src/main/java/com/teamnk/kimiljung/api/Tokens.kt
  app/src/main/java/com/teamnk/kimiljung/base/BaseActivity.kt
  app/src/main/java/com/teamnk/kimiljung/base/BaseFragment.kt
  app/src/main/java/com/teamnk/kimiljung/common/KimIlJeongApplication.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/enterbirthday/EnterBirthdayBottomSheetDialogFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/enterbirthday/EnterBirthdayViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/enterbirthday/EnterBirthdayViewModelFactory.kt
  app/src/main/java/com/teamnk/kimiljung/feature/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/login/LoginActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/register/RegisterActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/start/StartActivity.kt
  app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
  app/src/main/java/com/teamnk/kimiljung/util/Constans.kt
  app/src/main/java/com/teamnk/kimiljung/util/SharedPreferencesUtil.kt
  app/src/main/java/com/teamnk/kimiljung/util/StartActivityUtil.kt
  app/src/main/res/layout/activity_change_user_information.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: 기능 수정

#178 PR :: (#176) 게시글 라벨 기능 구현
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentAdapter.kt
  app/src/main/res/layout/activity_detail_post.xml
  app/src/main/res/layout/item_post.xml
Labels: 기능 추가

#180 PR :: (#179) edit comment
  app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentRepository.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentActivity.kt
Labels: 기능 수정

#181 PR :: (#Feature/135) 마이페이지 로직 구현
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordData.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/com/teamnk/kimiljung/feature/enterbirthday/EnterBirthdayBottomSheetDialogFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/introduction/IntroductionPagerActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/main/MainActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageFragment.kt
  app/src/main/java/com/teamnk/kimiljung/feature/mypage/MyPageViewModel.kt
Labels: 기능 추가, 기능 수정

#183 PR :: (#140) OkHttp Intercepter 구현
  app/src/main/java/com/teamnk/kimiljung/api/RetrofitClient.kt
  app/src/main/java/com/teamnk/kimiljung/api/Tokens.kt
Labels: 기능 추가, 기능 수정

#184 Feature/140 retrofit okhttp intercepter 구현
  app/src/main/java/com/teamnk/kimiljung/api/APIProvider.kt
  app/src/main/java/com/teamnk/kimiljung/api/Tokens.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationAPI.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/com/teamnk/kimiljung/feature/changeuserinformation/ChangeUserInformationViewModel.kt
Labels: 기능 추가, 기능 수정, 코드 리팩토링
