Repository team-nk/kim-il-jeong-android, pull requests merged in 2023-01, with the labels that each got.

#1 PR :: Feature/프로젝트 초기 설정
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/intellij-javadocs-4.0.1.xml
  .idea/misc.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/app/junsu/kimiljeong/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/di/application/KimIlJeongApplication.kt
  app/src/main/java/app/junsu/kimiljeong/di/module/NetworkModule.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/app/junsu/kimiljeong/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 기능 추가

#2 Feature/프로젝트 초기 설정
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/intellij-javadocs-4.0.1.xml
  .idea/misc.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/app/junsu/kimiljeong/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/di/application/KimIlJeongApplication.kt
  app/src/main/java/app/junsu/kimiljeong/di/module/NetworkModule.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/app/junsu/kimiljeong/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 코드 리팩토링

#4 PR :: Feature/액티비티 및 관련 컴포넌트 추가
  app/build.gradle
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_blue_checked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_blue_selector.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_blue_unchecked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_green_checked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_green_selector.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_green_unchecked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_purple_checked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_purple_selector.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_purple_unchecked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_red_checked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_red_selector.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_red_unchecked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_yellow_checked.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_yellow_selector.xml
  app/src/main/res/drawable-v24/bg_create_schedule_color_indicator_yellow_unchecked.xml
  app/src/main/res/drawable/bg_calendar_clndr.xml
  app/src/main/res/drawable/bg_calendar_date_today.xml
  app/src/main/res/drawable/bg_comment_et_primary.xml
  app/src/main/res/drawable/bg_create_schedule_btn_selected_date.xml
  app/src/main/res/drawable/bg_create_schedule_swch_off.xml
  app/src/main/res/drawable/bg_create_schedule_swch_on.xml
  app/src/main/res/drawable/bg_create_schedule_swch_thmb_off.xml
  app/src/main/res/drawable/bg_create_schedule_swch_thmb_on.xml
  app/src/main/res/drawable/bg_global_btn_delete.xml
  app/src/main/res/drawable/bg_global_btn_primary.xml
  app/src/main/res/drawable/bg_global_btn_secondary.xml
  app/src/main/res/drawable/bg_global_dlg_btm_sht.xml
  app/src/main/res/drawable/bg_global_et_primary.xml
  app/src/main/res/drawable/bg_introduction_vpgr_indicator.xml
  app/src/main/res/drawable/bg_main_bn.xml
  app/src/main/res/drawable/bg_post_comment_text_label.xml
  app/src/main/res/drawable/selector_bn_main_item_color.xml
  app/src/main/res/drawable/selector_create_schedule_swch.xml
  app/src/main/res/drawable/selector_create_schedule_swch_thmb.xml
  app/src/main/res/values/colors.xml
Labels: 기능 추가

#5 PR :: Feature/액티비티 및 관련 컴포넌트 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/presentation/view/changepassword/ChangePasswordActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/res/drawable/bg_create_schedule_btn_selected_time.xml
  app/src/main/res/drawable/ic_bn_main_calendar.xml
  app/src/main/res/drawable/ic_bn_main_map.xml
  app/src/main/res/drawable/ic_bn_main_my_page.xml
  app/src/main/res/drawable/ic_bn_main_notification.xml
  app/src/main/res/drawable/ic_global_add.xml
  app/src/main/res/drawable/ic_global_edit.xml
  app/src/main/res/drawable/ic_global_ping.xml
  app/src/main/res/drawable/ic_my_page_depth.xml
  app/src/main/res/drawable/ic_post_comment_send.xml
  app/src/main/res/drawable/ic_post_pencil.xml
  app/src/main/res/drawable/img_global_temp.jpeg
  app/src/main/res/drawable/img_introduction_1.png
  app/src/main/res/drawable/img_introduction_2.png
  app/src/main/res/drawable/img_introduction_3.png
  app/src/main/res/drawable/img_introduction_4.png
  app/src/main/res/drawable/img_introduction_next.png
  app/src/main/res/drawable/img_start_google.png
  app/src/main/res/drawable/img_start_kakao.png
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#8 PR :: (#7) BaseActivity 구현
  app/src/main/java/app/junsu/kimiljeong/presentation/view/base/BaseActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/base/BaseFragment.kt
Labels: 기능 추가

#9 PR :: Feature/login view 구현
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/debug/res/values/ic_launcher_background.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/res/drawable/bg_global_btn_primary.xml
  app/src/main/res/drawable/bg_post_comment_text_label.xml
  app/src/main/res/drawable/ic_app_logo.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가

#10 PR :: Feature/start activity view 퍼블리싱
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/presentation/view/start/StartActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#12 PR :: Feature/액티비티 및 관련 컴포넌트 추가
  app/src/main/java/app/junsu/kimiljeong/data/api/remote/AuthAPI.kt
  app/src/main/java/app/junsu/kimiljeong/data/api/remote/PostAPI.kt
  app/src/main/java/app/junsu/kimiljeong/data/common/HTTPStatusCode.kt
  app/src/main/java/app/junsu/kimiljeong/data/common/Tokens.kt
  app/src/main/java/app/junsu/kimiljeong/data/interceptor/RequestInterceptor.kt
  app/src/main/java/app/junsu/kimiljeong/data/interceptor/ResponseInterceptor.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/common/BirthdayBoyInformation.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/common/PostInformation.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/ChangeBirthdayRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/ChangePasswordRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/CreatePostRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/LoginRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/SignUpRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/UploadImageRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/BooleanResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/InquireBirthdayListResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/InquirePostListResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/LoginResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/RenewTokenResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/SelfInformationResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/UploadImageResponse.kt
  app/src/main/java/app/junsu/kimiljeong/di/module/NetworkModule.kt
Labels: 기능 추가

#14 PR :: Feature/액티비티 및 관련 컴포넌트 추가
  app/src/main/java/app/junsu/kimiljeong/data/api/remote/PostAPI.kt
  app/src/main/java/app/junsu/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/app/junsu/kimiljeong/data/common/Color.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/common/CommentInformation.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/common/PostInformation.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/common/ScheduleInformation.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/request/SpecificLocationOfScheduleListRequest.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/BooleanResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/InquireCommentListResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/model/remote/response/InquireScheduleListResponse.kt
  app/src/main/java/app/junsu/kimiljeong/data/util/TypeCastingUtil.kt
Labels: 기능 추가

#13 PR :: Feature/main activity bottom navigation publishing
  app/build.gradle
  app/src/debug/res/menu/menu_bottom_navigation_main.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/post/PostFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/include_global_header.xml
  app/src/main/res/layout/include_login_header.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: 기능 추가

#11 PR :: Feature/introduction pager activity publishing
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionAdapter.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/start/StartActivity.kt
  app/src/main/res/layout/activity_introduction.xml
  app/src/main/res/layout/item_introduction.xml
Labels: 기능 추가

#20 PR :: BASE_URL 은닉
  app/build.gradle
Labels: 기능 추가

#22 PR :: Feature/repository 구현
  app/src/main/java/com/gram/kimiljeong/data/api/remote/AuthAPI.kt
  app/src/main/java/com/gram/kimiljeong/data/api/remote/PostAPI.kt
  app/src/main/java/com/gram/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/UserRepository.kt
Labels: 기능 추가

#23 PR :: Feature/hilt module 구현
  app/src/main/java/app/junsu/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionAdapter.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/post/PostFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/start/StartActivity.kt
  app/src/main/java/com/gram/kimiljeong/data/api/remote/AuthAPI.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/implement/UserRepositoryImpl.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/interface/UserRepository.kt
  app/src/main/java/com/gram/kimiljeong/di/module/APIModule.kt
  app/src/main/java/com/gram/kimiljeong/di/module/NetworkModule.kt
  app/src/main/java/com/gram/kimiljeong/di/module/RepositoryModule.kt
  app/src/main/java/com/gram/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/java/com/gram/kimiljeong/presentation/viewmodel/changepassword/ChangePasswordViewModel.kt
Labels: 기능 추가

#21 PR :: Feature/view initialize
  app/src/main/java/app/junsu/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/changepassword/ChangePasswordActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/post/PostFragment.kt
  app/src/main/java/app/junsu/kimiljeong/presentation/view/start/StartActivity.kt
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/include_global_header.xml
  app/src/main/res/layout/include_login_header.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#25 PR :: Feature/mainviewmodel 구현
  app/src/main/java/com/gram/kimiljeong/data/common/CommonSharedPreferences.kt
  app/src/main/java/com/gram/kimiljeong/data/common/Tokens.kt
  app/src/main/java/com/gram/kimiljeong/data/common/preferences/AuthPreferences.kt
  app/src/main/java/com/gram/kimiljeong/data/common/preferences/AuthPreferencesImpl.kt
  app/src/main/java/com/gram/kimiljeong/data/extension/datastore.kt
  app/src/main/java/com/gram/kimiljeong/data/interceptor/HeaderAuthorizationInterceptor.kt
  app/src/main/java/com/gram/kimiljeong/data/interceptor/RequestInterceptor.kt
  app/src/main/java/com/gram/kimiljeong/data/interceptor/ResponseInterceptor.kt
  app/src/main/java/com/gram/kimiljeong/data/model/remote/common/PostInformation.kt
  app/src/main/java/com/gram/kimiljeong/data/model/remote/common/ScheduleInformation.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/implement/UserRepositoryImpl.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/origin/UserRepository.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/remote/implement/UserRepositoryImpl.kt
  app/src/main/java/com/gram/kimiljeong/data/repository/remote/origin/UserRepository.kt
  app/src/main/java/com/gram/kimiljeong/di/application/KimIlJeongApplication.kt
  app/src/main/java/com/gram/kimiljeong/di/module/ContextModule.kt
  app/src/main/java/com/gram/kimiljeong/di/module/NetworkModule.kt
  app/src/main/java/com/gram/kimiljeong/di/module/PreferencesModule.kt
  app/src/main/java/com/gram/kimiljeong/di/module/RepositoryModule.kt
  app/src/main/java/com/gram/kimiljeong/presentation/view/base/viewmodel/BaseViewModel.kt
  app/src/main/java/com/gram/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/java/com/gram/kimiljeong/presentation/viewmodel/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/com/gram/kimiljeong/presentation/viewmodel/main/MainViewModel.kt
Labels: 기능 추가

#34 PR :: Feature/로그인 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/data/common/preferences/AuthPreferences.kt
  app/src/main/java/team/nk/kimiljeong/data/common/preferences/AuthPreferencesImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/interceptor/HeaderAuthorizationInterceptor.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/UserRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/UserRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/viewmodel/BaseViewModel.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/changepassword/ChangePasswordActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/enterbirthday/EnterBirthdayBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/post/PostFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/register/RegisterActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/start/StartActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/login/LoginViewModel.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/main/MainViewModel.kt
  app/src/main/res/layout/activity_register.xml
Labels: 기능 추가

#35 PR :: Feature/mypage related view
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/presentation/view/changepassword/ChangePasswordActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/enterbirthday/EnterBirthdayBottomSheetDialogFragment.kt
  app/src/main/res/drawable/background_dialog_bottom_sheet.xml
  app/src/main/res/layout/activity_change_user_information.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가

#36 PR :: Feature/mypage related view
  app/src/main/res/layout/activity_comment.xml
  app/src/main/res/layout/activity_post_create.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/activity_post_history.xml
  app/src/main/res/layout/activity_post_inspect.xml
  app/src/main/res/layout/dialog_create_schedule.xml
  app/src/main/res/layout/dialog_double_button.xml
  app/src/main/res/layout/dialog_map_location.xml
  app/src/main/res/layout/dialog_search_location.xml
  app/src/main/res/layout/dialog_select_schedule.xml
  app/src/main/res/layout/dialog_select_specific_schedule.xml
  app/src/main/res/layout/dialog_single_button.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_post.xml
Labels: 기능 추가

#38 Feature/mainviewmodel 개인정보 조회 api 호출 로직 구현
  app/build.gradle
  app/src/main/java/team/nk/kimiljeong/presentation/view/adapter/bindingadapter/BindingAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/login/LoginViewModel.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/main/MainViewModel.kt
Labels: 기능 추가

#39 PR :: Feature/actionbar 제거
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/debug/res/values/ic_launcher_background.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가

#41 PR :: Feature/activityfragment showsnackbar 공통 인터페이스 구현 및 확장
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/common/ShowSnackBar.kt
Labels: 기능 추가

#44 PR :: scope function change
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
Labels: 코드 리팩토링

#48 PR :: Feature/회원가입 로직 구현
  app/src/main/java/team/nk/kimiljeong/presentation/view/adapter/bindingadapter/BindingAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/login/LoginActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/register/RegisterActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/register/RegisterViewModel.kt
Labels: 기능 추가

#54 PR :: Feature/id duplicated check logic
  app/src/main/java/team/nk/kimiljeong/presentation/view/register/RegisterActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/register/RegisterViewModel.kt
Labels: 기능 추가

#58 PR :: Feature/일별 일정 조회 구현
  app/src/main/java/team/nk/kimiljeong/data/model/remote/common/ScheduleInformation.kt
  app/src/main/java/team/nk/kimiljeong/presentation/adapter/recyclerviewadapter/ScheduleAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/calendar/CalendarViewModel.kt
Labels: 기능 추가

#62 PR :: Hotfix/일별 일정 조회
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/calendar/CalendarViewModel.kt
  app/src/main/res/layout/fragment_calendar.xml
Labels: 기능 추가

#65 PR :: hotfix/signup_fix
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/register/RegisterViewModel.kt
Labels: 코드 리팩토링

#63 PR :: Feature/로그아웃 기능 구현
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/logout/LogoutDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
Labels: 기능 추가

#69 PR :: Feature/게시글 작성 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/data/model/remote/request/CreatePostRequest.kt
  app/src/main/java/team/nk/kimiljeong/presentation/adapter/recyclerviewadapter/PostAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/common/VariousInformation.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/post/PostFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/postcreate/PostCreateActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/postinspect/PostInspectActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/comment/CommentViewModel.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/postcreate/PostCreateViewModel.kt
  app/src/main/res/layout/activity_post_create.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#67 PR :: Feature/change user information
  app/src/main/java/team/nk/kimiljeong/data/api/remote/AuthAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/model/remote/request/ChangeUserInformationRequest.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/UserRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/UserRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/changeinformation/ChangeUserInformationViewModel.kt
Labels: 기능 추가

#74 Feature/게시글 작성 구현
  app/src/main/java/team/nk/kimiljeong/data/interceptor/HeaderAuthorizationInterceptor.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/logout/LogoutDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/postcreate/PostCreateActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/selectschedule/SelectScheduleBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/postcreate/PostCreateViewModel.kt
  app/src/main/res/layout/activity_post_create.xml
Labels: 기능 추가

#80 Feature/78 마이페이지 기능들 재구성하기
  app/src/main/java/team/nk/kimiljeong/data/interceptor/HeaderAuthorizationInterceptor.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/changepassword/ChangePasswordActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/enterbirthday/EnterBirthdayBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/main/MainActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/changepassword/ChangePasswordViewModel.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/main/MainViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 코드 리팩토링, 버그 수정

#76 PR :: Feature/일정 생성 기능 구현
  app/.DS_Store
  app/build.gradle
  app/src/main/.DS_Store
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseMapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/util/ViewStatusUtil.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/DatePickerDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/TimePickerDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/SearchLocationDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/register/RegisterActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/schedule/AddScheduleBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/ScheduleViewModel.kt
  app/src/main/res/drawable/bg_create_schedule_edittext_cursor_black.xml
  app/src/main/res/layout/dialog_create_schedule.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/dialog_search_location.xml
  app/src/main/res/layout/dialog_time_picker.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle.properties
Labels: 기능 추가

#82 PR :: Feature/setting map map fragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/interceptor/HeaderAuthorizationInterceptor.kt
  app/src/main/java/team/nk/kimiljeong/data/model/remote/request/SpecificLocationOfScheduleListRequest.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/ScheduleRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/ScheduleRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/adapter/recyclerviewadapter/ScheduleAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseMapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/ScheduleDetailDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/SearchLocationDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/selectschedule/SelectScheduleBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/ScheduleViewModel.kt
  app/src/main/res/layout/dialog_schedule_detail.xml
  app/src/main/res/layout/fragment_map.xml
Labels: 기능 추가

#83 PR :: Feature/setting map map fragment
  app/src/main/java/team/nk/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/ScheduleRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/ScheduleRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/adapter/recyclerviewadapter/ScheduleAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseMapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/delete/DeleteDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/ScheduleDetailDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/ScheduleViewModel.kt
  app/src/main/res/drawable/bg_global_btn_error.xml
  app/src/main/res/layout/dialog_delete.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 기능 추가

#84 PR :: Feature/setting map map fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/interceptor/HeaderAuthorizationInterceptor.kt
  app/src/main/java/team/nk/kimiljeong/data/model/remote/request/CreateScheduleRequest.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/ScheduleRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/ScheduleRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/adapter/recyclerviewadapter/ScheduleAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/base/view/BaseMapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/TimePickerDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/delete/DeleteDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/ScheduleDetailDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/SearchLocationDialog.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/schedule/AddScheduleBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/ScheduleViewModel.kt
  app/src/main/res/layout/dialog_create_schedule.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/include_global_header.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#85 Feature/78 마이페이지 기능들 재구성하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/presentation/view/checkmypost/CheckMyPostActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_post_history.xml
Labels: 기능 추가

#87 PR :: Feature/86 show schedule detail on calendar
  app/src/main/java/team/nk/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/ScheduleRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/ScheduleRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/CalendarFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/calendar/ScheduleLocationBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/schedule/AddScheduleBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/ScheduleViewModel.kt
  app/src/main/res/layout/dialog_schedule_location.xml
Labels: 기능 추가

#89 Feature/78 마이페이지 기능들 재구성하기
  app/src/main/java/team/nk/kimiljeong/data/api/remote/ScheduleAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/ScheduleRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/ScheduleRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/adapter/recyclerviewadapter/SelectScheduleAdapter.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/map/MapFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/post/PostFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/postcreate/PostCreateActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/scheduleinformation/ScheduleInformationBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/selectschedule/SelectScheduleBottomSheetDialogFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/postcreate/PostCreateViewModel.kt
  app/src/main/res/layout/dialog_select_schedule.xml
Labels: 기능 추가

#90 PR :: Feature/88 image upload
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/team/nk/kimiljeong/data/api/remote/AuthAPI.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/implement/UserRepositoryImpl.kt
  app/src/main/java/team/nk/kimiljeong/data/repository/remote/origin/UserRepository.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/changeuserinformation/ChangeUserInformationActivity.kt
  app/src/main/java/team/nk/kimiljeong/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/team/nk/kimiljeong/presentation/viewmodel/changeinformation/ChangeUserInformationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 기능 추가
